# Confidence Scoring Weights
# These weights determine how different evidence types contribute to the
# overall confidence score during root cause analysis.

# Temporal sequence of events (proper cause→effect ordering)
temporal_sequence: 0.35

# Correlation strength between tags (weighted by lag)
correlation_strength: 0.25

# Anomaly severity (z-scores and duration)
anomaly_severity: 0.20

# Evidence consistency (multiple sources confirming the same story)
evidence_consistency: 0.20 